const mongoose = require('mongoose');

// Create a schema for LitterLogs
const litterLogSchema = new mongoose.Schema({
    location: {
        latitude: {
            type: Number,  // Latitude as a number
            required: true
        },
        longitude: {
            type: Number,  // Longitude as a number
            required: true
        }
    },
    timestamp: {
        type: Date,  // Time when the image was taken
        default: Date.now  // Defaults to current date/time
    },
    isDeleted: {
        type: Boolean,
        default: false
    }
});


const LitterLog = mongoose.model('LitterLog', litterLogSchema);

module.exports = LitterLog;

// bins can be created due to camera or user .
//if bin generated by camera , then bin's number will be null , if by user then bin's number will have user number
//for every bin , create a route 